# Site settings
title: Nominho's Dev Blog
email: ""
description: >-
  개발 경험과 기술을 기록하는 블로그입니다.
baseurl: ""
url: "https://beryl416.github.io"
github_username: beryl416

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme settings
minima:
  skin: dark
  date_format: "%Y-%m-%d"

# Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Pagination
show_excerpts: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
